import type { UnitDef } from "./types.js";

export const ALL_UNITS: UnitDef[] = [
  {
    id: "warlock",
    name: "Warlock",
    cls: "hex-mage",
    description: "A wielder of forbidden magic who drains the life from enemies to fuel their own power. The Warlock punishes aggression through curses and soul-shattering debuffs, growing stronger with every wound inflicted.",
    baseAttackStyle: "ranged-volley",
    primaryStat: "magAtk",
    baseHp: 90,
    physAtk: 25,
    magAtk: 65,
    physDef: 40,
    magDef: 50,
    speed: 38,
    moveDist: 2,
    evasion: 0.1,
    skills: [
      { id: "drain-life", name: "Drain Life", type: "special", power: 55, ap: 3, style: "ranged-direct", accuracy: 110, effect: "Heals Warlock for 50% of damage dealt" },
      { id: "curse", name: "Curse", type: "buff", ap: 2, style: "ranged-direct", accuracy: 105, effect: "Target takes +20% damage from all sources for 2 turns" },
      { id: "wither", name: "Wither", type: "buff", ap: 3, style: "ranged-volley", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "AoE 2×2 — MagAtk −20% on all hit for 2 turns" },
      { id: "soul-rend", name: "Soul Rend", type: "special", power: 70, ap: 3, style: "ranged-volley", accuracy: 105, effect: "+15 damage per active debuff on target" },
      { id: "doom", name: "Doom", type: "buff", ap: 3, style: "ranged-direct", accuracy: 105, effect: "Target takes 20 damage/turn for 3 turns" },
      { id: "necrotic-burst", name: "Necrotic Burst", type: "special", power: 65, ap: 5, style: "ranged-volley", accuracy: 90, aoe: { w: 4, h: 1 }, effect: "AoE full row" },
      { id: "spellblade", name: "Spellblade", type: "buff", ap: 4, style: "self", accuracy: 100, effect: "Swaps MagAtk and PhysAtk; base attacks become melee ethereal blade; can attack twice per turn for 5 turns" },
      { id: "soul-siphon", name: "Soul Siphon", type: "buff", ap: 3, style: "ranged-direct", accuracy: 105, effect: "Permanently drains 20 MagAtk from target, adding it to Warlock's MagAtk until Warlock is defeated" },
    ],
    passives: [
      { id: "spite", name: "Spite", description: "Attacker loses 1 AP whenever they hit Warlock." },
      { id: "hex-toll", name: "Hex Toll", description: "Debuffed enemies spend +1 extra AP to use any skill." },
      { id: "eldritch-blast", name: "Eldritch Blast", description: "Warlock fires two base attacks in one Attack action, each at 75% damage." },
    ],
  },
  {
    id: "paladin",
    name: "Paladin",
    cls: "guardian",
    description: "A divine warrior who leads from the front, shielding allies with sacred auras and rallying fallen comrades back to the fight. The Paladin rewards supporting teammates with surging AP gain.",
    baseAttackStyle: "melee",
    primaryStat: "physAtk",
    baseHp: 130,
    physAtk: 60,
    magAtk: 40,
    physDef: 65,
    magDef: 55,
    speed: 25,
    moveDist: 2,
    evasion: 0.05,
    skills: [
      { id: "holy-strike", name: "Holy Strike", type: "physical", power: 55, ap: 1, style: "melee", accuracy: 110, effect: "Basic blessed sword swing" },
      { id: "inspiring-strike", name: "Inspiring Strike", type: "physical", power: 30, ap: 2, style: "melee", accuracy: 110, effect: "If landed, adjacent allies gain +50% evasion for 2 turns" },
      { id: "shield-slam", name: "Shield Slam", type: "physical", power: 50, ap: 2, style: "melee", accuracy: 110, effect: "Target PhysDef −20% for 2 turns" },
      { id: "consecrating-slam", name: "Consecrating Slam", type: "special", power: 45, ap: 4, style: "melee", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "AoE 2×2 on opponent's side within melee reach" },
      { id: "smite", name: "Smite", type: "physical", power: 75, ap: 3, style: "melee", accuracy: 105, effect: "+30% damage vs debuffed targets" },
      { id: "aegis", name: "Aegis", type: "buff", ap: 2, style: "ally", accuracy: 100, effect: "Target ally takes −40% damage until end of the following turn" },
      { id: "divine-aura", name: "Divine Aura", type: "buff", ap: 5, style: "self", accuracy: 100, effect: "Paladin and adjacent allies gain +25% evasion and +25% PhysAtk for 5 turns" },
      { id: "blessed-ground", name: "Blessed Ground", type: "healing", ap: 4, style: "ally", accuracy: 100, aoe: { w: 2, h: 2 }, effect: "2×2 blessed field; allies inside heal 10 HP/turn for 3 turns" },
    ],
    passives: [
      { id: "holy-presence", name: "Holy Presence", description: "Adjacent allies take −15% damage from all sources." },
      { id: "devotion", name: "Devotion", description: "Gains +1 AP the first time each turn Paladin buffs or heals a teammate." },
      { id: "sacred-vow", name: "Sacred Vow", description: "When any ally drops to 0 HP, Paladin gains +2 AP immediately." },
    ],
  },
  {
    id: "knight",
    name: "Knight",
    cls: "blade-knight",
    description: "An immovable fortress in plate armor. The Knight absorbs punishment that would shatter lesser units, turning every defensive action into an advantage and protecting the party from overwhelming pressure.",
    baseAttackStyle: "melee",
    primaryStat: "physAtk",
    baseHp: 150,
    physAtk: 65,
    magAtk: 15,
    physDef: 80,
    magDef: 40,
    speed: 20,
    moveDist: 1,
    evasion: 0.05,
    skills: [
      { id: "slash", name: "Slash", type: "physical", power: 55, ap: 1, style: "melee", accuracy: 110, effect: "Reliable sword strike" },
      { id: "shield-bash", name: "Shield Bash", type: "physical", power: 45, ap: 2, style: "melee", accuracy: 110, effect: "Stuns target — they lose their next action" },
      { id: "challenge", name: "Challenge", type: "buff", ap: 2, style: "ranged-direct", accuracy: 105, effect: "Forces target to attack Knight next turn or take 25 chip damage" },
      { id: "fortress-stance", name: "Fortress Stance", type: "buff", ap: 2, style: "self", accuracy: 100, effect: "+40% PhysDef for 2 turns; Knight cannot move while active" },
      { id: "lance-charge", name: "Lance Charge", type: "physical", power: 70, ap: 4, style: "melee", accuracy: 105, effect: "Pierces through the entire column" },
      { id: "iron-wall", name: "Iron Wall", type: "buff", ap: 2, style: "self", accuracy: 100, effect: "Completely absorbs the next 50 damage received" },
      { id: "bulwark", name: "Bulwark", type: "buff", ap: 3, style: "ally", accuracy: 100, aoe: { w: 2, h: 2 }, effect: "All allies in a 2×2 area gain +25% PhysDef for 2 turns" },
      { id: "decisive-strike", name: "Decisive Strike", type: "physical", power: 90, ap: 4, style: "melee", accuracy: 105, effect: "Massive hit; Knight cannot move on its next turn" },
      { id: "last-bastion", name: "Last Bastion", type: "buff", ap: 4, style: "self", accuracy: 100, effect: "For one full turn, all damage dealt to any ally is redirected to Knight instead (using Knight's own defenses)" },
    ],
    passives: [
      { id: "steadfast", name: "Steadfast", description: "Knight cannot be displaced, pushed, or have its position altered by any effect." },
      { id: "iron-guard", name: "Iron Guard", description: "Knight's Defend provides 60% damage mitigation (vs the standard 40%) and grants +1 AP instead of 0." },
      { id: "ironclad", name: "Ironclad", description: "Knight takes −20% damage from all sources while at or above 50% HP." },
    ],
  },
  {
    id: "cleric",
    name: "Cleric",
    cls: "cleric",
    description: "A radiant healer whose devotion to the light manifests in miraculous restoration and divine protection. The Cleric keeps the party alive through overwhelming pressure and can even reverse certain death.",
    baseAttackStyle: "ranged-volley",
    primaryStat: "magAtk",
    baseHp: 90,
    physAtk: 20,
    magAtk: 55,
    physDef: 45,
    magDef: 78,
    speed: 30,
    moveDist: 2,
    evasion: 0.1,
    skills: [
      { id: "mend", name: "Mend", type: "healing", ap: 1, style: "ally", accuracy: 100, healAmount: 20, effect: "Restores 20 HP to a single ally" },
      { id: "holy-light", name: "Holy Light", type: "healing", ap: 2, style: "ally", accuracy: 100, healAmount: 40, effect: "Restores 40 HP to a single ally" },
      { id: "cleanse", name: "Cleanse", type: "buff", ap: 2, style: "ally", accuracy: 100, effect: "Removes all debuffs from target ally; that ally gains +1 AP" },
      { id: "inspire", name: "Inspire", type: "buff", ap: 3, style: "ally", accuracy: 100, effect: "Target ally gains +2 AP immediately" },
      { id: "benediction", name: "Benediction", type: "healing", ap: 3, style: "ally", accuracy: 100, aoe: { w: 2, h: 2 }, healAmount: 20, effect: "Restores 20 HP to all allies in 2×2 area" },
      { id: "purifying-wave", name: "Purifying Wave", type: "buff", ap: 3, style: "ally", accuracy: 100, aoe: { w: 2, h: 2 }, effect: "Removes all debuffs from all allies in area; each cleansed ally gains +1 AP" },
      { id: "sacred-ground", name: "Sacred Ground", type: "healing", ap: 4, style: "ally", accuracy: 100, aoe: { w: 2, h: 2 }, effect: "Allies inside regenerate 10 HP and +1 AP per turn for 3 turns" },
      { id: "divine-intervention", name: "Divine Intervention", type: "healing", ap: 5, style: "ally", accuracy: 100, healAmount: 30, effect: "Revives a KO'd ally at 30% HP with all debuffs removed" },
      { id: "holy-bolt", name: "Holy Bolt", type: "special", power: 50, ap: 2, style: "ranged-volley", accuracy: 110, effect: "Basic holy energy blast" },
      { id: "judgment", name: "Judgment", type: "special", power: 75, ap: 3, style: "ranged-direct", accuracy: 105, effect: "+5 bonus damage for each heal Cleric has performed this match" },
      { id: "holy-shell", name: "Holy Shell", type: "buff", ap: 3, style: "ally", accuracy: 100, aoe: { w: 2, h: 3 }, effect: "All allies in area gain +35% MagDef for 3 turns" },
    ],
    passives: [
      { id: "blessed-touch", name: "Blessed Touch", description: "Each time Cleric heals an ally, Cleric gains +1 AP." },
      { id: "mana-spring", name: "Mana Spring", description: "At the start of each turn, all adjacent allies gain +1 AP." },
      { id: "guardian-angel", name: "Guardian Angel", description: "The first time any ally would be KO'd each turn, Cleric automatically heals them for 15 HP (can prevent the KO)." },
    ],
  },
  {
    id: "mage",
    name: "Mage",
    cls: "invoker",
    description: "A brilliant but reckless arcane scholar who grows exponentially more dangerous as a battle progresses. The Mage's power snowballs with each spell cast, culminating in catastrophic area devastation.",
    baseAttackStyle: "ranged-volley",
    primaryStat: "magAtk",
    baseHp: 80,
    physAtk: 15,
    magAtk: 80,
    physDef: 25,
    magDef: 55,
    speed: 35,
    moveDist: 2,
    evasion: 0.1,
    skills: [
      { id: "arcane-bolt", name: "Arcane Bolt", type: "special", power: 55, ap: 2, style: "ranged-direct", accuracy: 110, effect: "Reliable magic shot" },
      { id: "frost-lance", name: "Frost Lance", type: "special", power: 60, ap: 2, style: "ranged-direct", accuracy: 110, effect: "Reduces target Speed by 15 for 2 turns" },
      { id: "arcane-surge", name: "Arcane Surge", type: "buff", ap: 2, style: "self", accuracy: 100, effect: "Next skill used this match deals +50% damage" },
      { id: "fireball", name: "Fireball", type: "special", power: 70, ap: 3, style: "ranged-volley", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "AoE 2×2 explosion" },
      { id: "chain-lightning", name: "Chain Lightning", type: "special", power: 65, ap: 3, style: "ranged-direct", accuracy: 110, effect: "Deals 60% damage to the nearest additional enemy" },
      { id: "blizzard", name: "Blizzard", type: "special", power: 55, ap: 4, style: "ranged-volley", accuracy: 90, aoe: { w: 3, h: 3 }, effect: "AoE 3×3; all hit units lose 10 Speed for 2 turns" },
      { id: "frost-barrier", name: "Frost Barrier", type: "buff", ap: 3, style: "self", accuracy: 100, effect: "Creates an ice wall intercepting the next direct attack; if triggered, Mage gains +3 AP; 3-turn cooldown" },
      { id: "arcane-cataclysm", name: "Arcane Cataclysm", type: "special", power: 120, ap: 7, style: "ranged-volley", accuracy: 90, aoe: { w: 3, h: 3 }, effect: "Ultimate AoE 3×3; requires significant AP buildup" },
    ],
    passives: [
      { id: "spell-mastery", name: "Spell Mastery", description: "After using 3 different skills in a match, all skill AP costs are reduced by 1 (minimum 1)." },
      { id: "overload", name: "Overload", description: "Each time Mage deals damage with a skill, gains +5 MagAtk permanently (stacks up to 5×)." },
      { id: "arcane-echo", name: "Arcane Echo", description: "30% chance any damaging skill bounces to a second random enemy target for 50% damage." },
    ],
  },
  {
    id: "rogue",
    name: "Rogue",
    cls: "fell-duelist",
    description: "A shadow operative who strikes without warning, poisons without conscience, and steals everything not nailed down — including your AP. The Rogue thrives on flanking, debuffing, and exploiting weakness.",
    baseAttackStyle: "melee",
    primaryStat: "physAtk",
    baseHp: 85,
    physAtk: 55,
    magAtk: 25,
    physDef: 35,
    magDef: 35,
    speed: 80,
    moveDist: 4,
    evasion: 0.2,
    skills: [
      { id: "backstab", name: "Backstab", type: "physical", power: 50, ap: 2, style: "melee", accuracy: 110, effect: "+50% damage if attacking from a non-frontal angle" },
      { id: "smokescreen", name: "Smokescreen", type: "buff", ap: 3, style: "self", accuracy: 100, effect: "Rogue's entire side is obscured for 2 turns; enemies cannot accurately target specific tiles" },
      { id: "shadowstep", name: "Shadowstep", type: "buff", ap: 1, style: "self", accuracy: 100, effect: "Teleports to any tile within Move Distance, ignoring blocking units" },
      { id: "poison-blade", name: "Poison Blade", type: "physical", power: 45, ap: 2, style: "melee", accuracy: 110, effect: "Target takes 10 damage/turn for 3 turns" },
      { id: "cheap-shot", name: "Cheap Shot", type: "physical", power: 40, ap: 2, style: "melee", accuracy: 110, effect: "Reduces target Speed by 20 for 2 turns" },
      { id: "death-mark", name: "Death Mark", type: "buff", ap: 3, style: "ranged-direct", accuracy: 105, effect: "Target takes +30% damage from all sources for 2 turns" },
      { id: "blade-flurry", name: "Blade Flurry", type: "physical", power: 40, ap: 3, style: "melee", accuracy: 95, effect: "Strikes 3 times; each hit checked for evasion separately" },
      { id: "marked-for-death", name: "Marked for Death", type: "physical", power: 85, ap: 4, style: "melee", accuracy: 105, effect: "Only usable if target has a debuff; always crits (×1.5)" },
      { id: "mug", name: "Mug", type: "physical", power: 30, ap: 2, style: "melee", accuracy: 110, effect: "Steals 2 AP from target on hit" },
      { id: "rip", name: "Rip", type: "buff", ap: 3, style: "melee", accuracy: 110, effect: "Strips one active buff from target and applies it to Rogue instead" },
      { id: "knock-off", name: "Knock Off", type: "physical", power: 25, ap: 2, style: "melee", accuracy: 110, effect: "Low damage; removes target's equipped item for the rest of the match" },
    ],
    passives: [
      { id: "sneak-attack", name: "Sneak Attack", description: "Hitting an enemy from a different row than Rogue adds +15% damage." },
      { id: "predator", name: "Predator", description: "Moving and attacking on the same turn deals +25% damage." },
      { id: "scout", name: "Scout", description: "In PvP: reveals opponent's queued action for one unit per turn; in PvE: Rogue can see fully hidden enemy intentions." },
    ],
  },
  {
    id: "archer",
    name: "Archer",
    cls: "rune-archer",
    description: "A marksman who builds momentum through precision. Every consecutive hit sharpens the Archer's aim to a razor's edge, rewarding consistent accuracy with escalating power and AP generation.",
    baseAttackStyle: "ranged-direct",
    primaryStat: "physAtk",
    baseHp: 100,
    physAtk: 72,
    magAtk: 40,
    physDef: 40,
    magDef: 40,
    speed: 50,
    moveDist: 2,
    evasion: 0.15,
    skills: [
      { id: "double-shot", name: "Double Shot", type: "physical", power: 35, ap: 2, style: "ranged-direct", accuracy: 110, effect: "Fires twice at the same target" },
      { id: "pinning-arrow", name: "Pinning Arrow", type: "physical", power: 45, ap: 2, style: "ranged-direct", accuracy: 110, effect: "Inflicts Root — target can't move for 1 turn" },
      { id: "crippling-shot", name: "Crippling Shot", type: "physical", power: 40, ap: 2, style: "ranged-direct", accuracy: 110, effect: "Reduces target PhysAtk by 20% for 2 turns" },
      { id: "marked-shot", name: "Marked Shot", type: "physical", power: 55, ap: 3, style: "ranged-direct", accuracy: 105, effect: "Target takes +20% damage from all sources for 2 turns" },
      { id: "piercing-arrow", name: "Piercing Arrow", type: "physical", power: 65, ap: 3, style: "ranged-direct", accuracy: 110, effect: "Ignores PhysDef" },
      { id: "volley", name: "Volley", type: "physical", power: 30, ap: 3, style: "ranged-volley", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "Hits all enemies in a 2-tile radius" },
      { id: "rain-of-arrows", name: "Rain of Arrows", type: "physical", power: 25, ap: 4, style: "ranged-volley", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "Hits all enemies in target zone 3 times" },
      { id: "steady-aim", name: "Steady Aim", type: "buff", ap: 1, style: "self", accuracy: 100, effect: "Next attack this turn gains +30% accuracy and +20% power" },
      { id: "sniper-shot", name: "Sniper Shot", type: "physical", power: 80, ap: 4, style: "ranged-direct", accuracy: 130, effect: "Range 10 tiles; ignores all blocking" },
    ],
    passives: [
      { id: "sharpshooter", name: "Sharpshooter", description: "Each successful hit adds +5% accuracy (stacks up to +30%); resets fully on a miss." },
      { id: "flow-state", name: "Flow State", description: "Every 2 landed hits grants +1 AP." },
      { id: "double-tap", name: "Double Tap", description: "Every other base attack fires twice (alternates: single → double → single → double)." },
    ],
  },
  {
    id: "berserker",
    name: "Berserker",
    cls: "blade-knight",
    description: "A warrior who thrives at the edge of death. The Berserker turns punishment into power — healing from wounds, surviving lethal blows, and growing more lethal with every kill.",
    baseAttackStyle: "melee",
    primaryStat: "physAtk",
    baseHp: 145,
    physAtk: 85,
    magAtk: 25,
    physDef: 45,
    magDef: 35,
    speed: 48,
    moveDist: 2,
    evasion: 0.1,
    skills: [
      { id: "cleave", name: "Cleave", type: "physical", power: 55, ap: 2, style: "melee", accuracy: 110, effect: "Hits target and one adjacent enemy" },
      { id: "reckless-strike", name: "Reckless Strike", type: "physical", power: 90, ap: 3, style: "melee", accuracy: 105, effect: "Deals 15% of damage dealt back to self" },
      { id: "bloodlust", name: "Bloodlust", type: "physical", power: 50, ap: 2, style: "melee", accuracy: 110, effect: "Heals self for 30% of damage dealt" },
      { id: "fury", name: "Fury", type: "buff", ap: 1, style: "self", accuracy: 100, effect: "Gain +15% PhysAtk for 2 turns; lose 5% max HP" },
      { id: "rampage", name: "Rampage", type: "physical", power: 40, ap: 4, style: "melee", accuracy: 95, effect: "Hits random enemies 3 times" },
      { id: "whirlwind", name: "Whirlwind", type: "physical", power: 45, ap: 3, style: "melee", accuracy: 110, effect: "Leap up to 4 spaces to an enemy-adjacent tile; deal damage to all enemies adjacent to that tile; return to start" },
      { id: "berserker-charge", name: "Berserker Charge", type: "physical", power: 70, ap: 3, style: "melee", accuracy: 110, effect: "Move 2 tiles then strike" },
      { id: "sunder", name: "Sunder", type: "physical", power: 60, ap: 3, style: "melee", accuracy: 110, effect: "Reduces target PhysDef by 25% for 2 turns" },
      { id: "last-stand", name: "Last Stand", type: "buff", ap: 2, style: "self", accuracy: 100, effect: "Below 25% HP: gain +40% PhysAtk until end of turn" },
      { id: "earth-rend", name: "Earth Rend", type: "physical", power: 50, ap: 8, style: "melee", accuracy: 100, effect: "Slams the ground; deals 50 power to outer 10 tiles and forces enemies into the 4 interior tiles; always hits" },
    ],
    passives: [
      { id: "frenzy", name: "Frenzy", description: "Each consecutive melee hit on the same target stacks +8% damage bonus; resets if Berserker switches targets." },
      { id: "undying", name: "Undying", description: "Once per match, survive a lethal hit at 1 HP instead of dying." },
      { id: "bloodthirst", name: "Bloodthirst", description: "Each kill restores 20% max HP." },
    ],
  },
  {
    id: "lancer",
    name: "Lancer",
    cls: "lancer",
    description: "A dragoon warrior who launches skyward and crashes down with lethal force. While airborne, completely untargetable and accumulating AP for a devastating landing — a high-risk, high-reward aerial predator.",
    baseAttackStyle: "melee",
    primaryStat: "physAtk",
    baseHp: 120,
    physAtk: 68,
    magAtk: 50,
    physDef: 60,
    magDef: 43,
    speed: 45,
    moveDist: 2,
    evasion: 0.1,
    skills: [
      { id: "lancet", name: "Lancet", type: "physical", power: 55, ap: 2, style: "melee", accuracy: 110, effect: "Drains 20% of damage dealt as HP" },
      { id: "jump", name: "Jump", type: "physical", power: 100, ap: 4, style: "melee", accuracy: 105, effect: "Becomes untargetable for 1 turn (+2 AP while airborne), then crashes down on chosen tile" },
      { id: "high-jump", name: "High Jump", type: "physical", power: 140, ap: 6, style: "melee", accuracy: 105, effect: "Airborne for 2 turns (+2 AP each turn); heavier crash landing damage" },
      { id: "skewer", name: "Skewer", type: "physical", power: 70, ap: 3, style: "melee", accuracy: 110, effect: "Pierces through target, also hitting the unit directly behind them" },
      { id: "steady-thrust", name: "Steady Thrust", type: "physical", power: 60, ap: 2, style: "melee", accuracy: 110, effect: "Ignores 30% of target's PhysDef" },
      { id: "dragon-fang", name: "Dragon Fang", type: "physical", power: 75, ap: 3, style: "melee", accuracy: 105, effect: "35% chance to inflict Armor Break (−25% PhysDef) for 2 turns" },
      { id: "impulse", name: "Impulse", type: "physical", power: 40, ap: 3, style: "melee", accuracy: 110, effect: "Hits all enemies in a straight line directly ahead" },
      { id: "spear-volley", name: "Spear Volley", type: "physical", power: 50, ap: 3, style: "ranged-volley", accuracy: 90, effect: "Hurls spear in an arc; range 8; hits a tile and all adjacent to it" },
      { id: "aerial-drive", name: "Aerial Drive", type: "physical", power: 65, ap: 3, style: "melee", accuracy: 110, effect: "Strikes target and one diagonal tile simultaneously" },
      { id: "dragons-roar", name: "Dragon's Roar", type: "magical", power: 60, ap: 3, style: "ranged-volley", accuracy: 90, effect: "Releases draconic energy; hits all enemies in a 2-tile radius" },
      { id: "tempest-lance", name: "Tempest Lance", type: "magical", power: 70, ap: 3, style: "ranged-direct", accuracy: 110, effect: "Wind-infused strike; reaches up to 4 tiles" },
    ],
    passives: [
      { id: "dragons-blood", name: "Dragon's Blood", description: "Lancer heals 20% max HP while airborne during Jump or High Jump." },
      { id: "spear-reach", name: "Spear Reach", description: "Base attacks naturally strike 2 spaces in a line, hitting the target and the unit directly behind them." },
      { id: "lance-mastery", name: "Lance Mastery", description: "Lancet heals an additional 10% of Lancer's max HP on top of the damage drained." },
    ],
  },
  {
    id: "wanderer",
    name: "Wanderer",
    cls: "fell-duelist",
    description: "A masterless swordsman with a hybrid physical-magical fighting style. Exceptionally evasive and mobile, the Wanderer chains attacks into devastating combos and grows more untouchable with each successful hit or dodge.",
    baseAttackStyle: "melee",
    primaryStat: "physAtk",
    baseHp: 110,
    physAtk: 72,
    magAtk: 55,
    physDef: 47,
    magDef: 48,
    speed: 75,
    moveDist: 3,
    evasion: 0.3,
    skills: [
      { id: "feint", name: "Feint", type: "buff", ap: 1, style: "self", accuracy: 100, effect: "Next offensive move on any future turn is a guaranteed crit" },
      { id: "rising-slash", name: "Rising Slash", type: "physical", power: 50, ap: 2, style: "melee", accuracy: 110, effect: "Upward strike; if Falling Edge is used after this turn, it crits" },
      { id: "falling-edge", name: "Falling Edge", type: "physical", power: 65, ap: 2, style: "melee", accuracy: 110, effect: "Downward strike; crits and gains +20 power if Rising Slash was used this turn" },
      { id: "shadow-step", name: "Shadow Step", type: "buff", ap: 2, style: "self", accuracy: 100, effect: "Move up to 3 tiles and gain +15% evasion for 2 turns" },
      { id: "phantom-strike", name: "Phantom Strike", type: "physical", power: 72, ap: 3, style: "melee", accuracy: 105, effect: "Teleport-slash; crits and ignores PhysDef if Shadow Step was used this turn" },
      { id: "mirage-veil", name: "Mirage Veil", type: "buff", ap: 4, style: "self", accuracy: 100, effect: "+40% evasion for 4 turns" },
      { id: "phantom-stance", name: "Phantom Stance", type: "buff", ap: 2, style: "self", accuracy: 100, effect: "Base attack transforms into 2 magical volleys for 5 turns; unlocks Arcane Tempest" },
      { id: "arcane-tempest", name: "Arcane Tempest", type: "magical", power: 85, ap: 6, style: "ranged-volley", accuracy: 90, effect: "Storm of magical blades hitting all enemies across the enemy grid; only usable while Phantom Stance is active" },
      { id: "wind-slash", name: "Wind Slash", type: "magical", power: 50, ap: 2, style: "ranged-direct", accuracy: 110, effect: "Blade of wind up to 4 tiles; if Elemental Surge follows, it crits" },
      { id: "blur", name: "Blur", type: "buff", ap: 1, style: "self", accuracy: 100, effect: "Gain +25% evasion until next turn" },
    ],
    passives: [
      { id: "nomads-instinct", name: "Nomad's Instinct", description: "Each successful attack or evasion raises evasion by +5%; resets fully when Wanderer takes a hit." },
      { id: "blade-flow", name: "Blade Flow", description: "Successful crits restore 2 AP." },
      { id: "ghost-stride", name: "Ghost Stride", description: "Movement costs 0 AP while Wanderer's total evasion is above 30%." },
    ],
  },
  {
    id: "shaman",
    name: "Shaman",
    cls: "cleric",
    description: "An ancient nature conduit whose slow movement belies terrifying battlefield control. The Shaman poisons, paralyzes, and entangles the enemy formation while regenerating from a deep well of earth energy.",
    baseAttackStyle: "ranged-direct",
    primaryStat: "magAtk",
    baseHp: 160,
    physAtk: 38,
    magAtk: 60,
    physDef: 60,
    magDef: 75,
    speed: 25,
    moveDist: 1,
    evasion: 0.05,
    skills: [
      { id: "wither-shaman", name: "Wither", type: "buff", ap: 1, style: "ranged-direct", accuracy: 105, effect: "Reduces target's PhysAtk by 10% for 1 turn" },
      { id: "spore-sting", name: "Spore Sting", type: "magical", power: 20, ap: 1, style: "ranged-direct", accuracy: 110, effect: "Small nature hit; 35% chance to poison target (6% max HP/turn for 2 turns)" },
      { id: "entangle", name: "Entangle", type: "buff", ap: 2, style: "ranged-direct", accuracy: 105, effect: "Roots single target for 1 turn" },
      { id: "poison-spores", name: "Poison Spores", type: "buff", ap: 2, style: "ranged-direct", accuracy: 105, effect: "Poisons target (8% max HP/turn for 3 turns)" },
      { id: "natures-embrace", name: "Nature's Embrace", type: "healing", ap: 3, style: "ally", accuracy: 100, healAmount: 30, effect: "Heals self or one ally for 30% of Shaman's MagAtk" },
      { id: "spore-cloud", name: "Spore Cloud", type: "magical", power: 35, ap: 3, style: "ranged-volley", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "Hits 2-tile radius; inflicts Paralysis (50% chance to be unable to act, −25% Speed each turn)" },
      { id: "regrowth", name: "Regrowth", type: "buff", ap: 4, style: "self", accuracy: 100, effect: "Shaman regenerates 7% max HP/turn for 4 turns and removes one debuff" },
      { id: "spore-veil", name: "Spore Veil", type: "buff", ap: 4, style: "ranged-volley", accuracy: 90, effect: "Reduces all enemies' MagAtk by 25% for 3 turns" },
      { id: "earthbind", name: "Earthbind", type: "buff", ap: 5, style: "ranged-volley", accuracy: 90, effect: "Roots all enemies in a 3×1 row for 1 turn; always hits" },
      { id: "mycelium-web", name: "Mycelium Web", type: "buff", ap: 5, style: "ranged-volley", accuracy: 90, effect: "Claims up to 4 tiles; enemies on or entering those tiles are slowed (movement costs double AP) for 5 turns" },
      { id: "grand-blight", name: "Grand Blight", type: "magical", ap: 7, style: "ranged-volley", accuracy: 100, effect: "Poisons all enemies for heavy DOT (12% max HP/turn for 3 turns); always hits" },
    ],
    passives: [
      { id: "thick-skin", name: "Thick Skin", description: "Incoming magical damage reduced by 20%." },
      { id: "spore-aura", name: "Spore Aura", description: "Enemies that hit Shaman with a melee attack have a 35% chance to be poisoned." },
      { id: "natures-bounty", name: "Nature's Bounty", description: "At the start of each turn, Shaman regenerates 5% max HP." },
    ],
  },
  {
    id: "bard",
    name: "Bard",
    cls: "invoker",
    description: "A versatile support and catalyst. The Bard's songs grant allies extra AP, clear debuffs, and transform the entire battle pace. Pick the right instrument subclass and reshape the entire flow of combat.",
    baseAttackStyle: "ranged-direct",
    primaryStat: "magAtk",
    baseHp: 100,
    physAtk: 50,
    magAtk: 63,
    physDef: 43,
    magDef: 60,
    speed: 48,
    moveDist: 2,
    evasion: 0.12,
    skills: [
      { id: "dissonance", name: "Dissonance", type: "magical", power: 25, ap: 1, style: "ranged-direct", accuracy: 110, effect: "Discordant note; deals minor damage and drains 1 AP from target" },
      { id: "inspire-bard", name: "Inspire", type: "buff", ap: 2, style: "ally", accuracy: 100, effect: "Grant one ally +2 AP immediately" },
      { id: "mend-bard", name: "Mend", type: "healing", ap: 2, style: "ally", accuracy: 100, effect: "Heal one ally for 20% of Bard's MagAtk" },
      { id: "mockery", name: "Mockery", type: "magical", power: 45, ap: 3, style: "ranged-direct", accuracy: 110, effect: "Deals damage and reduces target's MagAtk by 20% for 2 turns" },
      { id: "battle-hymn", name: "Battle Hymn", type: "buff", ap: 3, style: "ally", accuracy: 100, effect: "All allies gain +1 AP at the start of each of their next 2 turns" },
      { id: "cleanse-bard", name: "Cleanse", type: "buff", ap: 3, style: "ally", accuracy: 100, effect: "Remove all debuffs from one ally" },
      { id: "lullaby", name: "Lullaby", type: "buff", ap: 4, style: "ranged-volley", accuracy: 90, aoe: { w: 2, h: 2 }, effect: "65% chance to inflict Sleep on all enemies in a 2-tile radius for 1 turn" },
      { id: "war-song", name: "War Song", type: "buff", ap: 4, style: "ally", accuracy: 100, effect: "All allies gain +20% PhysAtk and MagAtk for 2 turns" },
      { id: "ballad-of-swiftness", name: "Ballad of Swiftness", type: "buff", ap: 4, style: "ally", accuracy: 100, effect: "All allies gain +25% Speed for 3 turns" },
      { id: "mass-cleanse", name: "Mass Cleanse", type: "buff", ap: 5, style: "ally", accuracy: 100, effect: "Remove all debuffs from all allies" },
      { id: "anthem-of-resilience", name: "Anthem of Resilience", type: "buff", ap: 5, style: "ally", accuracy: 100, effect: "All allies gain +25% PhysDef and MagDef for 3 turns" },
      { id: "magnum-opus", name: "Magnum Opus", type: "buff", ap: 7, style: "ally", accuracy: 100, effect: "All allies gain +3 AP and +15% to all stats for 2 turns" },
    ],
    passives: [
      { id: "encore", name: "Encore", description: "When any ally scores a kill, Bard gains 2 AP." },
      { id: "resonance", name: "Resonance", description: "All of Bard's buffs last 1 additional turn." },
      { id: "harmonics", name: "Harmonics", description: "Whenever Bard buffs an ally, Bard heals for 10% of their max HP." },
      { id: "swordsbard", name: "Swordsbard ♪", description: "Instrument subclass — Wield a sword: PhysAtk +10; base attacks deal 35 power scaling off PhysAtk. Grants an additional passive slot." },
      { id: "crossbowbard", name: "Crossbowbard ♪", description: "Instrument subclass — Equip two crossbows; Evasion +10%; base attacks target two enemies dealing 15 power each (Ranged-Direct, 8 spaces). Grants an additional passive slot." },
      { id: "harpbard", name: "Harpbard ♪", description: "Instrument subclass — Wield a harp; MagAtk +10; base attack is Ranged-Direct magical (30 power) vs enemies or can target allies to grant +1 AP instead. Grants an additional passive slot." },
    ],
  },
];

export function getUnitDef(id: string): UnitDef | undefined {
  return ALL_UNITS.find((u) => u.id === id);
}

export function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function assignRosters(): { rosterA: string[]; rosterB: string[] } {
  const ids = shuffleArray(ALL_UNITS.map((u) => u.id));
  return {
    rosterA: ids.slice(0, 6),
    rosterB: ids.slice(6, 12),
  };
}
